# Generated by Django 4.0.3 on 2022-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisos',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
