# Generated by Django 4.0.3 on 2023-01-10 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0004_turma_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
