# Generated by Django 4.0.3 on 2023-01-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_post_atividades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atividades',
            new_name='Atividade',
        ),
        migrations.AddField(
            model_name='post',
            name='turmaPertecente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
    ]
