# Generated by Django 4.0.3 on 2023-01-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_rename_atividades_atividade_post_turmapertecente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='turmaPertecente',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
