# Generated by Django 4.0.3 on 2023-02-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_turma_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='criacao',
        ),
        migrations.AddField(
            model_name='post',
            name='criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
