# Generated by Django 4.1.5 on 2023-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0013_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
