# Generated by Django 4.0.3 on 2023-06-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0014_alter_post_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdf/'),
        ),
    ]
