# Generated by Django 4.2.2 on 2023-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0015_alter_post_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
