# Generated by Django 4.0.3 on 2023-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
