# Generated by Django 4.0.3 on 2023-02-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FtPerfil',
        ),
    ]
